"""add fields in user table

Revision ID: 3403e714c09c
Revises: 5f007ea0c352
Create Date: 2024-11-27 23:26:03.065952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3403e714c09c'
down_revision: Union[str, None] = '5f007ea0c352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=False))
    op.add_column('users', sa.Column('expired_access', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('expired_refresh', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expired_refresh')
    op.drop_column('users', 'expired_access')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
